M48
; DRILL file {KiCad 6.0.6-3a73a75311~116~ubuntu20.04.1} date mar. 12 juil. 2022 22:33:25
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2022-07-12T22:33:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6-3a73a75311~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.450
%
G90
G05
T1
X117000Y-116000
T0
M30
